会場を株式会社インプレスに更新した
toshibee2430/ichiyasaGitSample pull request #1
Opened 2024-01-31 11:18 UTC by toshibee2430

### 変更内容
イベント開催会場を「株式会社インプレス」に更新しました．

### 背景
「株式会社インプレス」さんがイベント会場を提供してくださることになりました．

2024-01-31 11:37 UTC, toshibee2430G commented
修正ありがとうございます．問題ないのでマージします．

2024-01-31 11:51 UTC, toshibee2430G requested changes
変更依頼があるので保留とします．

2024-01-31 11:51 UTC, toshibee2430G commented on index.html
> +                        <p>株式会社インプレス イベントセミナー会場</p>
「株式会社アスキー」に変更してください．

2024-01-31 11:58 UTC, toshibee2430 commented on index.html
> +                        <p>株式会社インプレス イベントセミナー会場</p>
承知しました．

2024-01-31 11:58 UTC, toshibee2430 commented
変更依頼を対応しました，ご確認お願いします．

2024-01-31 12:00 UTC, toshibee2430G commented
確認しました，問題ありません．

2024-01-31 12:01 UTC, toshibee2430G approved these changes

2024-01-31 12:01 UTC, toshibee2430G commented
👍

2024-02-01 09:18 UTC, toshibee2430G commented
closedは取り消しなので，Reopenします．

2024-02-01 09:20 UTC, merged